#!/bin/sh

APP=microsoft-edge
version=$(wget -q https://repology.org/project/microsoft-edge/versions -O - | grep "newest version" | head -1 | grep -o -P '(?<=">).*(?=</a)' | sed 's/^.*>//')

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/tools/pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo 'app: '$APP'

ingredients:
  package: microsoft-edge-stable
  dist: stable
  script:
    - wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_'$version'-1_amd64.deb
  packages:
    - microsoft-edge-stable' >> recipe.yml;

./pkg2appimage ./recipe.yml;


cd ..;
mv ./tmp/$APP/$APP.AppDir/opt/microsoft/msedge/* ./tmp/$APP/$APP.AppDir/
rm ./tmp/$APP/$APP.AppDir/AppRun
cp ./tmp/$APP/$APP.AppDir/microsoft-edge ./tmp/$APP/$APP.AppDir/AppRun
cp ./tmp/$APP/$APP.AppDir/*256*png ./tmp/$APP/$APP.AppDir/$APP.png
version=$(exec ./tmp/microsoft-edge/microsoft-edge.AppDir/AppRun --version | grep -Eo "[+-]?[0-9]+([.][0-9]+)?+[+-]?[0-9]+([.][0-9]+)?")
ARCH=x86_64 ./tmp/appimagetool -n ./tmp/$APP/$APP.AppDir
mv ./Microsoft_Edge-*AppImage ./Microsoft_Edge-$version-x86_64.AppImage
rm -R -f ./tmp
