#!/bin/sh

APP=microsoft-edge

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget -q $(wget -q https://api.github.com/repos/probonopd/go-appimage/releases -O - | grep -v zsync | grep -i continuous | grep -i appimagetool | grep -i x86_64 | grep browser_download_url | cut -d '"' -f 4 | head -1) -O appimagetool
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/tools/pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo 'app: '$APP'

ingredients:
  package: microsoft-edge-stable
  dist: stable
  script: 
    - wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/'$(wget -q https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/ -O - | grep -Po '(?<=href=")[^"]*' | sort --version-sort | tail -1)'' >> recipe.yml;

./pkg2appimage ./recipe.yml;


cd ..;
mv ./tmp/$APP/$APP.AppDir/opt/microsoft/msedge/* ./tmp/$APP/$APP.AppDir/
rm ./tmp/$APP/$APP.AppDir/AppRun
cp ./tmp/$APP/$APP.AppDir/microsoft-edge ./tmp/$APP/$APP.AppDir/AppRun
cp ./tmp/$APP/$APP.AppDir/*256*png ./tmp/$APP/$APP.AppDir/$APP.png
version=$(exec ./tmp/microsoft-edge/microsoft-edge.AppDir/AppRun --version | grep -Eo "[+-]?[0-9]+([.][0-9]+)?+[+-]?[0-9]+([.][0-9]+)?")
ARCH=x86_64 VERSION=$(./tmp/appimagetool -v | grep -o '[[:digit:]]*') ./tmp/appimagetool -s ./tmp/$APP/$APP.AppDir
mv ./Microsoft_Edge-*AppImage ./Microsoft_Edge-$version-x86_64.AppImage
rm -R -f ./tmp
