#!/bin/sh

APP=microsoft-edge

mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget -q "$(wget -q https://api.github.com/repos/probonopd/go-appimage/releases -O - | sed 's/"/ /g; s/ /\n/g' | grep -o 'https.*continuous.*tool.*86_64.*mage$')" -O appimagetool
wget https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/tools/pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo 'app: '$APP'

ingredients:
  package: microsoft-edge-dev
  dist: stable
  script: 
    - wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/'$(curl -Ls https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/ | grep -Po '(?<=href=")[^"]*' | sort --version-sort | tail -1)'' >> recipe.yml;

./pkg2appimage ./recipe.yml;


cd ..;
cp ./tmp/$APP/$APP.AppDir/usr/share/applications/*.desktop ./tmp/$APP/$APP.AppDir/
mv ./tmp/$APP/$APP.AppDir/opt/microsoft/msedge-dev/* ./tmp/$APP/$APP.AppDir/
rm ./tmp/$APP/$APP.AppDir/AppRun
cp ./tmp/$APP/$APP.AppDir/microsoft-edge-dev ./tmp/$APP/$APP.AppDir/AppRun
cp ./tmp/$APP/$APP.AppDir/*256*png ./tmp/$APP/$APP.AppDir/$APP-dev.png
version=$(exec ./tmp/microsoft-edge/microsoft-edge.AppDir/AppRun --version | grep -Eo "[+-]?[0-9]+([.][0-9]+)?+[+-]?[0-9]+([.][0-9]+)?")
ARCH=x86_64 VERSION=$(./tmp/appimagetool -v | grep -o '[[:digit:]]*') ./tmp/appimagetool -s ./tmp/$APP/$APP.AppDir
mv ./Microsoft_Edge_"(dev)"-*AppImage ./Microsoft_Edge_"(dev)"-$version-x86_64.AppImage
rm -R -f ./tmp
